<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Cewka.AudioProbe</RootNamespace>
    <AssemblyName>Cewka.AudioProbe</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cewka.Audio\Cewka.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Concentus.OggFile" Version="1.0.7" />
  </ItemGroup>

</Project>
